# Generated by Django 4.2.7 on 2023-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_user_user_alter_goal_user_alter_userpair_donor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIDMap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
            ],
        ),
    ]
